[project]
name = "projet-filtre"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Brune", email = "brune.alirand@edu.devinci.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "pillow>=12.3.0",
    "scipy>=1.18.1",
]

[project.scripts]
projet-filtre = "projet_filtre:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
